# User config
author: "cpjags"
tagline: "Joaquin González"
description: "Creador de contenido multimedia."
keywords: "audiovisual, ingenieria audiovisual, multimedia design"
email: "cpjags@gmail.com"
linkedin: "https://www.linkedin.com/in/joaquin-gs/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed